version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser          # Your desired username
      POSTGRES_PASSWORD: mypassword  # Your desired password
      POSTGRES_DB: illini_shop_db    # Your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/illini_shop_db  # Use the same username/password as in the db service
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
